sudo: required
dist: precise
language: cpp

branches:
  only:
  - master

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages:
            - ['g++-5', 'cmake', 'cmake-data']
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'george-edison55-precise-backports']
          packages:
            - ['clang-3.7', 'cmake', 'cmake-data']
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libXmu-dev libXi-dev libgl-dev libxxf86vm-dev libvulkan-dev libglfw3-dev libglfw3 libglew-dev libglew1.13 libglm-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make